demo/cbv/urls.py
from django.urls import path, re_path

from . import views


# 创建子路由
urlpatterns = [

    # path("路由url","视图函数","路由别名")
    # django类视图的路由绑定
    # path("路径/", views.视图类名.as_view()),   # as_view获取客户端本次HTTP请求，POST，GET，PUT
    path("user/", views.UserView.as_view()),   # as_view获取客户端本次HTTP请求，POST，GET，PUT
    

]

demo/demo/urls.py
from django.contrib import admin
from django.urls import path, include

import demoapp.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('demoapp/', include("demoapp.urls")),
    path('polls/', include("polls.urls")),
    path('goods/', include("goods.urls", namespace="goods")),      # 路由前缀的别名，也叫命名空间


    # 设置路由的第二种方式：直接在总路由配置
    # path('demoapp/', demoapp.views.index)

    # 请求参数的获取
    path('demorequest/', include("demorequest.urls")),   
    path('cookie/', include('mycookie.urls')),
    path('sess/', include("sess.urls")),     # session功能学习
    path('user/', include("user.urls")),
    path('tem/', include("tem.urls")),
    path('djdemo/', include("djdemo.urls")),
    path('bytedance/', include("bytedance.urls")),
    path('cbv/', include("cbv.urls")),
    path('student/', include("student.urls")),

]

demo/polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:question_id>/", views.detail, name="detail"),
    path("<int:question_id>/results/", views.results, name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

# 创建子路由
# urlpatterns = [
#     # path("", views.index, name="index"),
#     # ex: /polls/
#     path("", views.index, name="index"),
#     # ex: /polls/5/
#     path("<int:question_id>/", views.detail, name="detail"),
#     # ex: /polls/5/results/
#     path("<int:question_id>/results/", views.results, name="results"),
#     # ex: /polls/5/vote/
#     path("<int:question_id>/vote/", views.vote, name="vote"),
#     # added the word 'specifics'
#     path("specifics/<int:question_id>/", views.detail, name="detail"),  
    
# ]

demo/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.




class Question(models.Model):
    def __str__(self):
        return self.queestion_text
    
    queestion_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):

    def __str__(self):
        return self.choice_text

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

demo/polls/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from .models import Question
from django.shortcuts import get_object_or_404, render
from django.http import Http404



def index(request):

    latest_question_list = Question.objects.order_by("-pub_date")[:5]

    context = {"latest_question_list": latest_question_list}
    return render(request, "polls/index.html", context)

    # template = loader.get_template("polls/index.html")
    # context = {
    #     "latest_question_list": latest_question_list,
    # }
    # return HttpResponse(template.render(context, request))
    # output = ", ".join([q.question_text for q in latest_question_list])
    # return HttpResponse(output)
    # return HttpResponse("Hello, world. You're at the polls index.")


def detail(request, question_id):

    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/detail.html", {"question": question})

    # try:
    #     question = Question.objects.get(pk=question_id)
    # except Question.DoesNotExist:
    #     raise Http404("Question does not exist")
    # return render(request, "polls/detail.html", {"question": question})
    # return HttpResponse("You're looking at question %s." %question_id)

def results(request, question_id):
    response = "You're looking at the result of question %s."
    return HttpResponse(response % question_id)


def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

demo/polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {{ question }}
    <h1>{{ question.queestion_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>
</body>
</html>

demo/polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    

    {% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="/polls/{{ question.id }}/">{{ question.queestion_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
<li><a href="/polls/{{ question.id }}/">{{ question.queestion_text }}</a></li>
<li><a href="{% url 'detail' question.id %}">{{ question.queestion_text }}</a></li>

<li><a href="{% url 'detail' question.id %}">{{ question.queestion_text }}</a></li>

<li><a href="{% url 'polls:detail' question.id %}">{{ question.quesetion_text }}</a></li>
</body>
</html>